2020-11-11 21:36:21,093 DEBUG   MainThread:17940 [git_repo.py:repo():30] git repository is invalid
